### ISSUE TITLE
ChoreoSpectrum3D Dataset

### ISSUE THREAD

**Issue by xiaoyaoshengy** [fluide1022/EnchantDance#1]
Hello, thanks for sharing the work! When can we get access to the ChoreoSpectrum3D Dataset?

**Comment by fluide1022** [comment]
We will public the ChoreoSpectrum3D Dataset. Please wait for two weeks. Thanks for your attention

**Comment by GuangtaoLyu** [comment]
> We will public the ChoreoSpectrum3D Dataset. Please wait for two weeks. Thanks for your attention

hello？when will you release the dataset？
